spring:
  main:
    allow-circular-references: true
    lazy-initialization: false

  application:
    name: ServicesApplication
    baseUrl: http://localhost:8080

  datasource:
    url: jdbc:postgresql://localhost:5432/basketBallCamp
    username: postgres
    password: postgres
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
